env:
  browser: true
  es2021: true
  node: true
extends:
- 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
rules:
  array-callback-return: 2
  complexity:
  - 1
  - 20
  eqeqeq: 2
  max-statements:
  - 1
  - 40
  max-statements-per-line:
  - 1
  - max: 1
  max-nested-callbacks:
  - 1
  - 2
  max-depth:
  - 1
  - max: 2
  max-lines:
  - 1
  - 200
  no-eval: 2
  no-return-assign: 2
  no-param-reassign: 1
  no-var: 2
  prefer-const: 2
